accounts/urls.py
from django.urls import path, include
from . import views
from django_filters.views import FilterView
from django.contrib.auth.decorators import login_required

app_name = 'accounts'

urlpatterns = [
    path('', login_required(views.SearchView.as_view()), name='transaction_search'),
    path('report', login_required(views.MonthlyReportView.as_view()), name='transaction_report'),
	path('record/<int:pk>/', login_required(views.TransactionDetailView.as_view()), name='transaction_detail'),
    path('record/create/', login_required(views.TransactionCreate.as_view()), name='transaction_create'),
    path('record/update/<int:pk>/', login_required(views.TransactionUpdate.as_view()), name='transaction_update'),
    path('record/delete/<int:pk>/', login_required(views.TransactionDelete.as_view()), name='transaction_delete'),
    path('record/receipt/<int:pk>/', login_required(views.generate_receipt), name='generate_receipt'),
]

ar_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.conf import settings
from accounts.views import signup_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    url(r'^login/$', auth_views.LoginView.as_view(), {'next_page': settings.LOGIN_REDIRECT_URL}, name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^signup/$', signup_view, name='signup'),

    # path('accounts/', include('django.contrib.auth.urls')),
]

accounts/models.py
from django.db import models
from datetime import datetime, date, timedelta
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MaxValueValidator, MinValueValidator

def format_date(date_obj):
	formatedDate = date_obj.strftime("%Y%m%d")
	return str(formatedDate)

class Transaction(models.Model):
    transact_id = models.BigAutoField(primary_key=True)
    transact_date = models.DateField(default=date.today, verbose_name="Transaction Date")
    owner = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name="Owner")
    creator = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name="Creator")

    def __str__(self):
        return str(self.transact_id)

    def get_absolute_url(self):
        return reverse('accounts:transaction_detail', kwargs={'pk': self.pk})

class TransactionDetails(models.Model):
    transactDet_id = models.BigAutoField(primary_key=True)
    transactDet_desc = models.CharField(default='', max_length = 250, verbose_name = "Desc.")
    rm = models.DecimalField(default = 0, decimal_places = 2, max_digits=10, null = True, blank=True, verbose_name = "RM")
    usd = models.DecimalField(default = 0, decimal_places = 2, max_digits=10, null = True, blank=True, verbose_name = "USD")
    rmb = models.DecimalField(default = 0, decimal_places = 2, max_digits=10, null = True, blank=True, verbose_name = "RMB")
    transaction = models.ForeignKey(Transaction, on_delete = models.CASCADE, related_name="transaction_details")

    def __str__(self):
        return str(self.transactDet_id)
    
    class Meta:
        verbose_name = 'Transaction Detail'
        verbose_name_plural = 'Transaction Details'


class Profile(models.Model):
    BHANTE = 1
    SAYALAY = 2
    OFFICE_ADMIN = 3
    ROLE_CHOICES = (
        (BHANTE, 'Bhante'),
        (SAYALAY, 'Sayalay'),
        (OFFICE_ADMIN, 'Office Admin'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, null=True, blank=True)

    def __str__(self):  # __unicode__ for Python 2
        return self.user.username

@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

accounts/forms.py
from django import forms
from .models import *
from django.forms.models import inlineformset_factory
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Fieldset, Div, HTML, ButtonHolder, Submit, Reset
from .custom_layout_object import *
from datetime import datetime
from django.contrib.auth.forms import UserCreationForm

class TransactionDetailsForm(forms.ModelForm):
    transactDet_desc = forms.CharField(
        widget=(forms.Textarea(attrs={'rows':'3', 'cols':'100'})),label='Desc.'
    )
    class Meta:
        model = Transaction
        fields='__all__'

TransactionDetailsFormSet = inlineformset_factory(
    Transaction, TransactionDetails, form=TransactionDetailsForm,
    fields='__all__', can_delete=True, min_num=1, validate_min=True, extra=0
    )


class TransactionForm(forms.ModelForm):
    
    transact_date = forms.DateField(
        widget=forms.TextInput(attrs={'type': 'date', 'value': datetime.now().strftime("%Y-%m-%d")}),label='Transaction Date'
    )

    class Meta:
        model = Transaction
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(TransactionForm, self).__init__(*args, **kwargs)
        self.fields['owner'].queryset = User.objects.select_related().filter(profile__role=1) | User.objects.select_related().filter(profile__role=2)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.layout = Layout(
            Div(
                Div(
                    Fieldset('Transaction details',
                        Field('transact_date'),
                        Field('owner'),
                        ), 
                        HTML("<br>"),
                        css_class='col-md-12',),
                Div(
                    Fieldset('Add Transactions',
                        Formset('transactions')),
                    css_class='m-3',),
                HTML("<br>"),
            css_class='row',),
            Div(ButtonHolder(Submit('submit', 'Save')), css_class="m-1"),
        )


class FilterForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(FilterForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_method = 'get'
        self.helper.layout = Layout(
            Div(
                Div(
                    Fieldset('Transaction Details',
                        Field('transaction__transact_id'),
                        Field('transaction__transact_date'),
                        Field('transaction__owner'),
                        Field('transaction__creator'),
                        Field('transactDet_desc'),
                        ),
                        HTML("<br>"),
                        css_class='col-md-12',),
                Div(
                    ButtonHolder(
                        Submit('submit', 'Search'),
                    ),
                    css_class="col text-center"),
                css_class='row',
            )
        )

class MonthlyReportForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(MonthlyReportForm, self).__init__(*args, **kwargs)
        self.fields['transaction__transact_date'].widget.attrs.update({'class': 'form-control'})
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_method = 'get'
        self.helper.layout = Layout(
            Div(
                Div(
                    Fieldset('Transaction Details',
                        Field('transaction__transact_date'),
                        Field('transaction__owner'),
                    ),
                    HTML("<br>"),
                    css_class='col-md-12',),
                Div(
                    ButtonHolder(
                        Submit('submit', 'Search'),
                    ),
                    css_class="col text-center"),
                css_class='row',
            )
        )

class SignUpForm(UserCreationForm):
    role = forms.ChoiceField(choices=Profile.ROLE_CHOICES, help_text='Required. Select user\'s role.')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password1', 'password2', 'role')

accounts/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db import transaction
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.template import loader
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django_tables2.config import RequestConfig
from crispy_forms.layout import Button, Reset, Submit
from crispy_forms.layout import HTML as crispy_HTML
from .models import Profile
from django.db.models import Q
from calendar import monthrange
from datetime import date

from .tables import *
from .models import *
from .forms import *
from .filters import *
##########################################################################
#                           Invoice views                             #
##########################################################################

#modified from https://dev.to/zxenia/django-inline-formsets-with-class-based-views-and-crispy-forms-14o6
#repo https://github.com/zxenia/example-inline-formsets

class TransactionDetailView(DetailView):
    model = Transaction
    template_name = 'accounts/transaction_detail.html'

    def get_context_data(self, **kwargs):
        # qs = Product.objects.filter(invoice__invoice_id__iexact = self.object.invoice_id).select_related('invoice')
        qs = TransactionDetails.objects.filter(transaction__transact_id__iexact = self.object.transact_id)
        table = TransactionDetailTable(qs)
        context = super(TransactionDetailView, self).get_context_data(**kwargs)
        context['table'] = table
        return context

class TransactionCreate(CreateView):
    model = Transaction
    template_name = 'accounts/transaction_create.html'
    form_class = TransactionForm

    def get_context_data(self, **kwargs):
        data = super(TransactionCreate, self).get_context_data(**kwargs)
        data['title'] = 'Transaction Form'
        if self.request.POST:
            data['transactions'] = TransactionDetailsFormSet(self.request.POST)
        else:
            data['transactions'] = TransactionDetailsFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        transactions = context['transactions']
        with transaction.atomic():
            form.instance.creator = self.request.user
            if transactions.is_valid():
                self.object = form.save()
                transactions.instance = self.object
                transactions.save()
                return super(TransactionCreate, self).form_valid(form)
            else:
                return self.render_to_response(self.get_context_data(form=form))

    def get_success_url(self):
        return reverse_lazy('accounts:transaction_detail', kwargs={'pk': self.object.pk})


class TransactionUpdate(UpdateView):
    model = Transaction
    form_class = TransactionForm
    template_name = 'accounts/transaction_create.html'

    def get_context_data(self, **kwargs):
        data = super(TransactionUpdate, self).get_context_data(**kwargs)
        data['title'] = 'Update Transactions'
        if self.request.POST:
            data['transactions'] = TransactionDetailsFormSet(self.request.POST, instance=self.object)
        else:
            data['transactions'] = TransactionDetailsFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        transactions = context['transactions']
        with transaction.atomic():
            form.instance.creator = self.request.user
            if transactions.is_valid():
                self.object = form.save()
                transactions.instance = self.object
                transactions.save()
                return super(TransactionUpdate, self).form_valid(form)
            else:
                return self.render_to_response(self.get_context_data(form=form))

    def get_success_url(self):
        return reverse_lazy('accounts:transaction_detail', kwargs={'pk': self.object.pk})


class TransactionDelete(DeleteView):
    model = Transaction
    template_name = 'accounts/confirm_delete.html'

# ##########################################################################
# #                           Generate pdf                             #
# ##########################################################################

# https://gist.github.com/pikhovkin/5642563
# https://github.com/Kozea/WeasyPrint/issues/92
def generate_receipt(request, pk):
    trans_dets = get_object_or_404(TransactionDetails, pk=pk)
    date_str = date.today().strftime("%d-%m-%Y")
    trans_date_str = trans_dets.transaction.transact_date.strftime("%Y%m%d")
    template = loader.get_template('accounts/receipt.html')
    
    role_int = trans_dets.transaction.owner.profile.role
    role = ''
    if role_int == 1:
        role = 'Bhante'
    elif role_int == 2:
        role = 'Sayalay'
    
    context = {
        'name': role + ' ' + trans_dets.transaction.owner.username,
        'amount': trans_dets.rm,
        'date': date_str,
        'filename': 'ref_{}_{}_{}'.format(trans_date_str,  trans_dets.transaction.transact_id, trans_dets.transactDet_id),
    }
    return HttpResponse(template.render(context, request))

##########################################################################
#                           Search views                             #
##########################################################################

#modified from https://stackoverflow.com/questions/36871987/django-filter-change-default-form-appearance
#good ref https://kuttler.eu/en/post/using-django-tables2-filters-crispy-forms-together/

class SearchView(ListView):
    template_name = 'accounts/search.html'

    def get(self, request):
        transactionDetails_list = TransactionDetails.objects.all()
        transactionDetails_filter = TransactionDetailsFilter(request.GET, queryset=transactionDetails_list)

        #render reset and clear button dynamically
        has_filter = any(field in request.GET for field in set(transactionDetails_filter.get_fields()))
        helper = transactionDetails_filter.form.helper
        if has_filter:
            button_html = crispy_HTML('<a href="{%  url "accounts:transaction_search" %}" class="btn btn-warning">Reset</a>')
            helper.layout[0][1][0].append(button_html)
        else:
            helper.layout[0][1][0].append(Reset('reset', "Clear", css_class='btn btn-warning'))

        #populate result table with pagination
        result_table = TransactionDetailSearchTable(transactionDetails_filter.qs)
        RequestConfig(request, paginate={"per_page": 5}).configure(result_table)

        return render(request, self.template_name, {
            'filter': transactionDetails_filter,
            'table': result_table,
        })

##########################################################################
#                           Sign up views                             #
##########################################################################

def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.profile.role = form.cleaned_data.get('role')
            user.save()
            return redirect('accounts:transaction_search')
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})

##########################################################################
#                           Monthly report views                             #
##########################################################################

class MonthlyReportView(ListView):
    template_name = 'accounts/monthly_report.html'
    def get(self, request):
        transactionDetails_list = TransactionDetails.objects.all()
        transactionDetails_filter = MonthlyReportFilter(request.GET, queryset=transactionDetails_list)

        #render reset and clear button dynamically
        has_filter = any(field in request.GET for field in set(transactionDetails_filter.get_fields()))
        helper = transactionDetails_filter.form.helper
        if has_filter:
            button_html = crispy_HTML('<a href="{%  url "accounts:transaction_report" %}" class="btn btn-warning">Reset</a>')
            helper.layout[0][1][0].append(button_html)
        else:
            helper.layout[0][1][0].append(Reset('reset', "Clear", css_class='btn btn-warning'))

        #populate result table with pagination
        result_table = MonthlyReportTable(transactionDetails_filter.qs)
        RequestConfig(request).configure(result_table)
        date_str = date.today().strftime("%d-%m-%Y")

        return render(request, self.template_name, {
            'filter': transactionDetails_filter,
            'table': result_table,
            'date': date_str,
        })

accounts/templates/accounts/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}">
    {% block css %}
    {% endblock %}
    <title>Allowable Requisite System</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Allowable Requisite System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav" data-hover="dropdown" data-animations="fadeInDown fadeInRight fadeInUp fadeInLeft">
          <ul class="nav navbar-nav">
            <li class="nav-item dropdown" active>
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Transaction
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item {% if request.resolver_match.url_name == 'transaction_create' %}active{% endif %}" href="{% url 'accounts:transaction_create' %}">Create Transaction</a>
                <a class="dropdown-item {% if request.resolver_match.url_name == 'monthly_report' %}active{% endif %}" href="{% url 'accounts:transaction_report' %}">Report</a>
              </div>
            </li>
            <li class="nav-item dropdown" active>
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Management
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item {% if request.resolver_match.url_name == 'signup' %}active{% endif %}" href="{% url 'signup' %}">Create User</a>  
              </div>
            </li>
          </ul>
          {% if user.is_authenticated %}
            <a class="ml-auto btn btn-secondary" type="submit" href="{% url 'logout'%}">Logout <span class="badge badge-light">{{ user.username }}</span></a>
          {% endif %}
        </div>
      </nav>
    </header>
    <div class="container pt-4">
    {% block content %}

    {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'bootstrap/js/jquery-3.4.1.slim.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    
    {% block js %}
    
    {% endblock %}
  </body>
</html>

accounts/templates/accounts/confirm_delete.html
{% extends "accounts/transaction_detail.html" %}
{% block content %}
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Confirm delete</h3>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <h4>
                        Are you sure you want to delete: <strong>Transaction ID {{ object.transact_id }}</strong> ?
                    </h4>
                    <input  class="btn btn-danger" type="submit" value="Yes, I want to delete" />
                </form>
            </div>
            <div class="modal-footer">
                <input  class="btn btn-outline-secondary" type="submit" value="Cancel" onclick="goBack()" />
            </div>
        </div>
    </div>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock content %}

accounts/templates/accounts/formset.html
{% load crispy_forms_tags %}
{% load static %}
{% comment %} <table class="col-md-9" style="margin-left: 10px;"> {% endcomment %}
<table style="margin-left: 10px; border-collapse: separate;border-spacing: 10px;">
{{ formset.management_form|crispy }}

    {% for form in formset.forms %}
        <tr>
            <td></td>
            <td colspan="3" align="center">Allowable Requisite Eqv. To</td>
            <td></td>
            <td></td>
        </tr>
        <tr class="{% cycle 'row1' 'row2' %} formset_row-{{ formset.prefix }}">
            {% for field in form.visible_fields %}
                <td>
                    {# Include the hidden fields in the form #}
                    {% if forloop.first %}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                    {% endif %}
                    {{ field.errors.as_p }}
                    {{ field|as_crispy_field }}
                </td>
            {% endfor %}
        </tr>
    {% endfor %}

</table>
<br>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="{% static 'accounts/libraries/django-dynamic-formset/jquery.formset.js' %}"></script>
<script type="text/javascript">
    $('.formset_row-{{ formset.prefix }}').formset({
        addText: 'Add Record',
        deleteText: 'Remove',
        prefix: '{{ formset.prefix }}',
        addCssClass: 'btn btn-outline-primary btn-sm',
        deleteCssClass: 'btn btn-outline-danger btn-sm',
    });
</script>

accounts/templates/accounts/monthly_report.html
{% extends "accounts/base.html" %}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/report.css' %}">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h3>Report <span id="print_date"> generated on {{ date }}</span></h3>
            </div>
            <div class="card-body">
                <form action="" method="get">
                    {% crispy filter.form%}
                </form>
            </div>
        </div>
        <br/>
        {% render_table table %}
    </div>
{% endblock%}
{% block js %}
  <script src="{% static 'accounts/js/report.js' %}"></script>
{% endblock %}

accounts/templates/accounts/receipt.html
{% load static %}
{% load custom_tag %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ filename }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/receipt.css' %}">
</head>
<body>
    <table class="report-container">
        <thead class="report-header">
        <tr>
            <th class="report-header-cell">
            <div>
                Offering of Allowable Requisite 供养如法资具
            </div>
            </th>
        </tr>
        </thead>
        <tbody class="report-content">
        <tr>
            <td class="report-content-cell">
                <div class="main">
                    <div class="report-box">
                        <table cellpadding="0" cellspacing="0">
                            <tr>
                                <td>
                                    <b style="float:left">Ref. No.: {{ filename }}</b>
                                    <b style="float:right">Date: {{ date }}</b>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    {{ name }},
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div>I/We, <input type="text" value="Enter donor's name" name="donor_eng"> wish to offer {{ name }} the allowable requisites to the value of RM {{ amount }}.</div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div>If you need any allowable requisites, please request them from your kappiya <input type="text" value="Enter kappiya's name" name="kpy_eng">.</div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div>我/我们, <input type="text" value="Enter donor's name" name="donor_ch" required> 想供养您如法必需品，价值相当于 RM {{ amount }}.</div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div>如果您有任何需要，请向 <input type="text" value="Enter kappiya's name" name="kpy_ch"> 索取。</div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <p style="text-align:center;margin:5px;font-weight: bold;">Sādhu Sādhu Sādhu</p>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
    <hr style="border: 1px dashed black;" class="line"/>
    <div style="text-align: center; padding-top: 20px">
        <input id="print" type="button" value="Print" onclick="window.print()" style="width: 90px;height: 40px;">
    </div>
</body>
<script src="{% static 'accounts/js/jquery.min.js' %}"></script>
<script src="{% static 'accounts/js/receipt.js' %}"></script>
</html>

accounts/templates/accounts/search.html
{% extends "accounts/base.html" %}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}
{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h3>Search Transactions</h3>
            </div>
            <div class="card-body">
                <form action="" method="get">
                    {% crispy filter.form%}
                </form>
            </div>
        </div>
        <br/>
        {% render_table table %}
    </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "accounts/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="card">
        <div class="card-header">
            <h3>Create User</h3>
        </div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Sign up</button>
          </form>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/transaction_create.html
{% extends "accounts/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h3>{{ title }}</h3>
        </div>
        <div class="card-body">
             {% crispy form %}
        </div>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/transaction_detail.html
{% extends "accounts/base.html" %}
{% load render_table from django_tables2 %}
{% block content %}

<div class="container">   
<div class="card">
    <div class="card-header">
        <h3>Transaction</h1>
    </div>
    <div class="card-body">
        <table class="table">
            {% if object.transact_id %}
                <tr>
                    <th>Transaction ID:</th>
                    <td>{{ object.transact_id}}</td>
                </tr>
            {% endif %}
            {% if object.transact_date %}
                <tr>
                    <th>Transaction Date:</th>
                    <td>{{ object.transact_date | date:'d-m-Y' }}</td>
                </tr>
            {% endif %}
            {% if object.owner %}
                <tr>
                    <th>Transaction Owner:</th>
                    <td>{{ object.owner }}</td>
                </tr>
            {% endif %}
            {% if object.creator %}
                <tr>
                    <th>Transaction Creator:</th>
                    <td>{{ object.creator }}</td>
                </tr>
            {% endif %}
        </table>
        <br/>
        {% render_table table %}
        
        <div>
            <a class="btn btn-primary" href="{% url 'accounts:transaction_update' pk=object.transact_id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'accounts:transaction_delete' pk=object.transact_id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
  {% load static %}
  <script src="{% static 'accounts/js/transaction_detail.js' %}"></script>
{% endblock %}